### ISSUE TITLE
Mobile: Clicking in the navigation should dismiss it

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning#41] opened 2019-09-21 15:40 UTC
**Describe the bug**
On mobile devices, we have a mobile navigation menu. Clicking within it navigates to a new page, but the navigation itself does not dismiss. It should go away once a new page is navigated to.

**To Reproduce**
1. Open Awesome Learning on mobile
2. Click on the navigation
3. Click on a page

**Expected behavior**
Navigation should disappear

**Comment by Eshno** [comment] 2019-09-30 12:45
Hello! is this the navigation menu you're referring to? 

<img width="248" alt="Screen Shot 2019-09-30 at 8 41 57 AM" src="https://user-images.githubusercontent.com/34465493/65879619-3230ca00-e35e-11e9-83f6-ba831c8d8390.png">

If so, I'm unable to reproduce this issue on mobile.

**Comment by Cooperbuilt** [comment] 2019-09-30 13:20
That's the one!

**Comment by smcveigh941** [comment] 2019-10-03 19:11
Hey @Cooperbuilt , I second @Eshno comment. I am not able to reproduce this. Could you confirm if this is still an issue?

**Comment by Cooperbuilt** [comment] 2019-10-03 21:34
Not able to repro either - closing. Thanks y'all!

**Closed** 2019-10-05 18:46 UTC
Labels: enhancement, good first issue, hacktoberfest
